import PptxGenJS from "pptxgenjs";
import type { Customer, Ticket } from "./types";
import { ticketLogText } from "./domain";
import { formatDateTime } from "./utils";

const navy = "102536", teal = "1F6F8B", cyan = "3F91AD", ink = "172033", muted = "667085", line = "DFE5EE", pale = "F4F7FB", white = "FFFFFF";
function title(slide: PptxGenJS.Slide, heading: string, eyebrow: string) { slide.background = { color: white }; slide.addShape("rect", { x: 0, y: 0, w: 13.333, h: .16, fill: { color: teal }, line: { color: teal } }); slide.addText(eyebrow.toUpperCase(), { x: .6, y: .45, w: 5, h: .2, fontFace: "Prompt", fontSize: 8, bold: true, color: teal, charSpacing: 1.5, margin: 0 }); slide.addText(heading, { x: .6, y: .72, w: 11.8, h: .45, fontFace: "Prompt", fontSize: 24, bold: true, color: ink, margin: 0 }); slide.addShape("line", { x: .6, y: 1.35, w: 12.1, h: 0, line: { color: line, width: 1 } }); }
function footer(slide: PptxGenJS.Slide, customer: string, month: string) { slide.addText(`SupportDesk MD Control  |  ${customer}  |  ${month}`, { x: .6, y: 7.12, w: 8, h: .16, fontFace: "Prompt", fontSize: 7, color: muted, margin: 0 }); slide.addText("Internal & confidential", { x: 10.8, y: 7.12, w: 1.9, h: .16, align: "right", fontFace: "Prompt", fontSize: 7, color: muted, margin: 0 }); }
function metric(slide: PptxGenJS.Slide, x: number, y: number, label: string, value: string, accent = teal) { slide.addShape("roundRect", { x, y, w: 2.85, h: 1.15, rectRadius: .06, fill: { color: pale }, line: { color: line } }); slide.addShape("rect", { x, y, w: .08, h: 1.15, fill: { color: accent }, line: { color: accent } }); slide.addText(label.toUpperCase(), { x: x + .25, y: y + .2, w: 2.3, h: .18, fontFace: "Prompt", fontSize: 7, bold: true, color: muted, charSpacing: 1, margin: 0 }); slide.addText(value, { x: x + .25, y: y + .52, w: 2.3, h: .34, fontFace: "Prompt", fontSize: 21, bold: true, color: ink, margin: 0 }); }
function countBy(tickets: Ticket[], field: keyof Ticket) { return Object.entries(tickets.reduce<Record<string, number>>((acc, ticket) => { const key = String(ticket[field] || "Unspecified"); acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]); }
function distribution(slide: PptxGenJS.Slide, x: number, y: number, heading: string, rows: [string, number][], total: number) { slide.addText(heading, { x, y, w: 5.6, h: .28, fontFace: "Prompt", fontSize: 13, bold: true, color: ink, margin: 0 }); rows.slice(0, 7).forEach(([label, value], index) => { const yy = y + .48 + index * .56; slide.addText(label.replace(/_/g, " "), { x, y: yy, w: 2.25, h: .2, fontFace: "Prompt", fontSize: 9, color: ink, margin: 0 }); slide.addShape("roundRect", { x: x + 2.3, y: yy + .01, w: 2.55, h: .14, rectRadius: .04, fill: { color: "E8EDF2" }, line: { transparency: 100 } }); slide.addShape("roundRect", { x: x + 2.3, y: yy + .01, w: Math.max(.08, 2.55 * (value / Math.max(total, 1))), h: .14, rectRadius: .04, fill: { color: index % 2 ? cyan : teal }, line: { transparency: 100 } }); slide.addText(String(value), { x: x + 4.98, y: yy - .03, w: .4, h: .2, align: "right", fontFace: "Prompt", fontSize: 9, bold: true, color: ink, margin: 0 }); }); }

async function toBuffer(output: string | ArrayBuffer | Blob | Uint8Array) {
  if (output instanceof Uint8Array) return Buffer.from(output);
  if (output instanceof ArrayBuffer) return Buffer.from(output);
  if (typeof output === "string") return Buffer.from(output, "binary");
  return Buffer.from(await output.arrayBuffer());
}

export async function generateMonthlyReport(customer: Customer, allTickets: Ticket[], month: string) { const tickets = allTickets.filter((ticket) => ticket.customerKey === customer.key && ticket.date.slice(0, 7) === month); const open = tickets.filter((ticket) => !["closed", "cancelled", "resolved"].includes(ticket.kanbanStatus)); const breached = open.filter((ticket) => ticket.dueDate && new Date(ticket.dueDate) < new Date()); const used = tickets.filter((ticket) => ticket.chargeable).reduce((sum, ticket) => sum + ticket.mdUsed, 0); const pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "SupportDesk MD Control"; pptx.subject = `${customer.customerName} monthly support report`; pptx.title = `${customer.customerName} - ${month}`; pptx.company = "SupportDesk"; pptx.theme = { headFontFace: "Prompt", bodyFontFace: "Prompt" };
  let slide = pptx.addSlide(); slide.background = { color: navy }; slide.addShape("ellipse", { x: 9.7, y: -1.5, w: 5.2, h: 5.2, fill: { color: cyan, transparency: 84 }, line: { transparency: 100 } }); slide.addShape("ellipse", { x: -1.5, y: 5.1, w: 4.2, h: 4.2, fill: { color: teal, transparency: 72 }, line: { transparency: 100 } }); slide.addText("SUPPORTDESK", { x: .75, y: .65, w: 2.6, h: .25, fontFace: "Prompt", fontSize: 10, bold: true, color: "7FC2D8", charSpacing: 2, margin: 0 }); slide.addText("Monthly Support\nService Report", { x: .75, y: 2.0, w: 7.2, h: 1.35, fontFace: "Prompt", fontSize: 34, bold: true, color: white, breakLine: false, margin: 0 }); slide.addText(customer.customerName, { x: .78, y: 3.65, w: 6.6, h: .42, fontFace: "Prompt", fontSize: 18, color: "D7E8EE", margin: 0 }); slide.addText(`${month}  •  ${customer.projectCode}  •  ${customer.contractType}`, { x: .78, y: 4.25, w: 7.2, h: .28, fontFace: "Prompt", fontSize: 10, color: "93A8B5", margin: 0 }); slide.addText("MD CONTROL", { x: 10.35, y: 6.65, w: 2.1, h: .23, align: "right", fontFace: "Prompt", fontSize: 8, bold: true, color: "7FC2D8", charSpacing: 2, margin: 0 });
  slide = pptx.addSlide(); title(slide, "Executive summary", "Monthly overview"); metric(slide, .65, 1.75, "Tickets logged", String(tickets.length)); metric(slide, 3.65, 1.75, "Open items", String(open.length), "E9A23B"); metric(slide, 6.65, 1.75, "SLA breached", String(breached.length), "CF5F69"); metric(slide, 9.65, 1.75, "Monthly MD used", used.toFixed(2), "45A27C"); slide.addShape("roundRect", { x: .65, y: 3.35, w: 12, h: 2.75, rectRadius: .05, fill: { color: pale }, line: { color: line } }); slide.addText("Service health", { x: .95, y: 3.65, w: 3, h: .25, fontFace: "Prompt", fontSize: 13, bold: true, color: ink, margin: 0 }); slide.addText(breached.length ? `${breached.length} active ticket${breached.length === 1 ? " is" : "s are"} past the recorded due date and require attention.` : "No currently open ticket in this reporting month is past its recorded due date.", { x: .95, y: 4.1, w: 5.3, h: .65, fontFace: "Prompt", fontSize: 11, color: muted, breakLine: false, margin: 0 }); slide.addText("Contract position", { x: 6.8, y: 3.65, w: 3, h: .25, fontFace: "Prompt", fontSize: 13, bold: true, color: ink, margin: 0 }); slide.addText(`${customer.mdUsed.toFixed(2)} of ${customer.mdPurchased.toFixed(2)} maintenance days consumed. ${customer.mdRemaining.toFixed(2)} MD remaining (${customer.mdStatus}).`, { x: 6.8, y: 4.1, w: 5.2, h: .65, fontFace: "Prompt", fontSize: 11, color: muted, breakLine: false, margin: 0 }); footer(slide, customer.customerName, month);
  slide = pptx.addSlide(); title(slide, "Ticket composition", "Volume and distribution"); distribution(slide, .75, 1.75, "Status", countBy(tickets, "kanbanStatus"), tickets.length); distribution(slide, 6.85, 1.75, "Issue type", countBy(tickets, "issueType"), tickets.length); footer(slide, customer.customerName, month);
  slide = pptx.addSlide(); title(slide, "Priority and effort", "Service demand"); distribution(slide, .75, 1.75, "Severity", countBy(tickets, "severity"), tickets.length); distribution(slide, 6.85, 1.75, "Owner", countBy(tickets, "owner"), tickets.length); footer(slide, customer.customerName, month);
  slide = pptx.addSlide(); title(slide, "Maintenance-day usage", "Contract consumption"); metric(slide, .75, 1.7, "Purchased", customer.mdPurchased.toFixed(2)); metric(slide, 3.75, 1.7, "Lifetime used", customer.mdUsed.toFixed(2), "7C6BD2"); metric(slide, 6.75, 1.7, "Remaining", customer.mdRemaining.toFixed(2), customer.mdRemaining < 0 ? "CF5F69" : "45A27C"); metric(slide, 9.75, 1.7, "This month", used.toFixed(2), cyan); slide.addText("Utilization", { x: .8, y: 3.5, w: 2, h: .25, fontFace: "Prompt", fontSize: 12, bold: true, color: ink, margin: 0 }); slide.addShape("roundRect", { x: .8, y: 4.05, w: 11.7, h: .34, rectRadius: .08, fill: { color: "E8EDF2" }, line: { transparency: 100 } }); slide.addShape("roundRect", { x: .8, y: 4.05, w: 11.7 * Math.min(Math.max(customer.burnRate, 0), 100) / 100, h: .34, rectRadius: .08, fill: { color: customer.burnRate >= 100 ? "CF5F69" : customer.burnRate >= 80 ? "E9A23B" : teal }, line: { transparency: 100 } }); slide.addText(`${customer.burnRate.toFixed(1)}% consumed`, { x: .8, y: 4.58, w: 3, h: .25, fontFace: "Prompt", fontSize: 11, bold: true, color: ink, margin: 0 }); slide.addText(customer.renewalAlert || "No renewal alert recorded for this contract.", { x: .8, y: 5.2, w: 11.7, h: .5, fontFace: "Prompt", fontSize: 10, color: muted, margin: 0 }); footer(slide, customer.customerName, month);
  slide = pptx.addSlide(); title(slide, "Ticket detail", "Monthly activity"); const detailRows = tickets.slice(0, 14).map((ticket) => [ticket.issueId, ticket.issueTitle.slice(0, 48), ticket.severity, ticket.status.replace(/^\d{2}\s*-\s*/, ""), ticket.owner || "-", ticket.mdUsed.toFixed(2)]); slide.addTable([["Issue ID", "Title", "Priority", "Status", "Owner", "MD"], ...detailRows] as never, { x: .65, y: 1.65, w: 12, h: 4.9, border: { color: line, pt: .6 }, fill: { color: white }, color: ink, fontFace: "Prompt", fontSize: 7.5, margin: .06, rowH: .3, bold: false, colW: [1.15, 4.3, .8, 1.55, 2.4, .7] }); footer(slide, customer.customerName, month);
  slide = pptx.addSlide(); title(slide, "Pending and action required", "Follow-up"); const pending = open.length ? open : tickets.filter((ticket) => ticket.kanbanStatus === "waiting"); if (pending.length) slide.addTable([["Issue", "Action / log", "Owner", "Due"], ...pending.slice(0, 10).map((ticket) => [ticket.issueId, ticketLogText(ticket) || ticket.issueTitle, ticket.owner || "Unassigned", formatDateTime(ticket.dueDate)])] as never, { x: .7, y: 1.75, w: 11.9, border: { color: line, pt: .6 }, fontFace: "Prompt", fontSize: 8, color: ink, margin: .08, colW: [1.3, 6.4, 2.35, 1.5] }); else { slide.addText("No pending actions recorded for this reporting period.", { x: .8, y: 2.2, w: 11.6, h: .6, fontFace: "Prompt", fontSize: 18, bold: true, color: "45A27C", align: "center", margin: 0 }); } footer(slide, customer.customerName, month);
  const safeName = customer.customerName.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase(); const fileName = `${safeName}-${month}-${Date.now()}.pptx`; const bytes = await toBuffer(await pptx.write({ outputType: "nodebuffer" })); return { outputPath: `reports/generated/${fileName}`, fileName, bytes, summary: { tickets: tickets.length, open: open.length, breached: breached.length, mdUsed: used } };
}
