import { describe, expect, it } from "vitest";
import {
  createServiceNowWriteCommandRequestSchema,
  serviceNowCreateIncidentInputSchema,
  serviceNowSafeResponseSummarySchema,
  serviceNowUpdateIncidentInputSchema,
} from "./schemas";

describe("ServiceNow write schemas", () => {
  it("accepts a bounded create Incident command", () => {
    const input = {
      commandType: "create_incident",
      sourceType: "manual",
      manualOperationToken: "a".repeat(120),
      payload: {
        shortDescription: "Cannot open document",
        description: "The document viewer reports a bounded test error.",
        impact: "2",
        urgency: "2",
        externalReferences: { supperTicket: "TICKET-100" },
      },
    };
    expect(createServiceNowWriteCommandRequestSchema.parse(input)).toEqual(input);
  });

  it("rejects missing required create fields", () => {
    expect(() => serviceNowCreateIncidentInputSchema.parse({ description: "Only a description" })).toThrow();
  });

  it.each([
    [{ sysId: "a".repeat(32), state: "99" }, "state"],
    [{ sysId: "a".repeat(32), impact: "4" }, "impact"],
    [{ sysId: "a".repeat(32), urgency: "0" }, "urgency"],
  ])("rejects invalid bounded update values in %s", (input, field) => {
    expect(field).toBeTruthy();
    expect(() => serviceNowUpdateIncidentInputSchema.parse(input)).toThrow();
  });

  it("requires a target and at least one update field", () => {
    expect(() => serviceNowUpdateIncidentInputSchema.parse({ shortDescription: "Updated" })).toThrow();
    expect(() => serviceNowUpdateIncidentInputSchema.parse({ sysId: "a".repeat(32) })).toThrow();
    expect(() => serviceNowUpdateIncidentInputSchema.parse({
      sysId: "a".repeat(32),
      number: "INC100",
      state: "2",
    })).toThrow(/Exactly one/i);
  });

  it("requires lowercase 32-character sys_ids for reference fields", () => {
    expect(() => serviceNowCreateIncidentInputSchema.parse({
      shortDescription: "Test",
      description: "Test",
      callerId: "A".repeat(32),
    })).toThrow();
    expect(serviceNowCreateIncidentInputSchema.parse({
      shortDescription: "Test",
      description: "Test",
      callerId: "a".repeat(32),
      assignmentGroup: "b".repeat(32),
      customer: "c".repeat(32),
    })).toMatchObject({ callerId: "a".repeat(32) });
  });

  it("requires source entity and operation references for non-manual commands", () => {
    expect(() => createServiceNowWriteCommandRequestSchema.parse({
      commandType: "create_incident",
      sourceType: "supper_ticket",
      payload: { shortDescription: "Test", description: "Test" },
    })).toThrow();
    expect(createServiceNowWriteCommandRequestSchema.parse({
      commandType: "create_incident",
      sourceType: "supper_ticket",
      sourceEntityReference: "ticket:T-100",
      operationReference: "create:initial",
      payload: { shortDescription: "Test", description: "Test" },
    })).toMatchObject({
      sourceEntityReference: "ticket:T-100",
      operationReference: "create:initial",
    });
  });

  it("keeps manual operation identity server-owned", () => {
    expect(() => createServiceNowWriteCommandRequestSchema.parse({
      commandType: "create_incident",
      sourceType: "manual",
      operationReference: "caller-controlled",
      payload: { shortDescription: "Test", description: "Test" },
    })).toThrow(/generated by the server/i);
  });

  it("rejects credential-like external reference keys", () => {
    expect(() => serviceNowCreateIncidentInputSchema.parse({
      shortDescription: "Test",
      description: "Test",
      externalReferences: { apiToken: "not-allowed" },
    })).toThrow(/sensitive/i);
  });

  it("rejects arbitrary properties and oversized journal content", () => {
    expect(() => createServiceNowWriteCommandRequestSchema.parse({
      commandType: "add_comment",
      sourceType: "manual",
      operationReference: "comment:test",
      payload: { sysId: "a".repeat(32), text: "ok", rawResponse: {} },
    })).toThrow();
    expect(() => createServiceNowWriteCommandRequestSchema.parse({
      commandType: "add_work_note",
      sourceType: "manual",
      operationReference: "work-note:test",
      payload: { sysId: "a".repeat(32), text: "x".repeat(20_001) },
    })).toThrow();
  });

  it("requires complete matching marker hashes for a verified post-create proof", () => {
    const markerHash = "a".repeat(64);
    const valid = {
      httpStatus: 201,
      sysId: "b".repeat(32),
      number: "INC0010001",
      mutationCandidateObserved: true,
      candidateSysId: "b".repeat(32),
      candidateNumber: "INC0010001",
      mutationHttpStatus: 201,
      postWriteMarkerVerified: true,
      postWriteLookupHttpStatus: 200,
      postWriteLookupCorrelationMarkerHash: markerHash,
      postWriteVerifiedCorrelationMarkerHash: markerHash,
    };
    expect(serviceNowSafeResponseSummarySchema.parse(valid)).toEqual(valid);
    expect(() => serviceNowSafeResponseSummarySchema.parse({
      ...valid,
      postWriteVerifiedCorrelationMarkerHash: "c".repeat(64),
    })).toThrow(/marker proof/i);
    expect(() => serviceNowSafeResponseSummarySchema.parse({
      ...valid,
      postWriteLookupCorrelationMarkerHash: null,
    })).toThrow();
  });
});
